name: Build C# Backend

on:
  push:
    branches:
      - main

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build on aarch64
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Build artifacts
        id: build
        with:
          arch: aarch64
          distro: alpine_latest

          githubToken: ${{ github.token }}

          dockerRunArgs: |
            --volume "${{ github.workspace }}:/workspace"

          shell: /bin/sh

          install: |
            apk update
            apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib wget ca-certificates
            update-ca-certificates

          run: |
            bash /workspace/automation/dotnet-install.sh -c 5.0
            /bin/dotnet publish /workspace/CSharpMongoGraphqlSubscriptions.csproj -c Release -o /workspace/artifacts

      - name: Publish artifacts
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ${PWD}/artifacts.zip ${{ github.workspace }}/artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: ${PWD}/artifacts.zip
