name: Build C# Backend

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.*

jobs:
  build_job:
    runs-on: ubuntu-20.04
    name: Build on aarch64
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set environment variables
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build
        id: build
        run: |
          wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y apt-transport-https tar dotnet-sdk-5.0
          dotnet publish ${{ github.workspace }}/CSharpMongoGraphqlSubscriptions.csproj -c Release -r linux-arm64 -o ${{ github.workspace }}/artifacts --self-contained true
          tar -czvf ${{ github.workspace }}/brewcontroller.tar.gz -C ${{ github.workspace }}/artifacts .

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/brewcontroller.tar.gz
