name: Build C# Backend

on:
  push:
    branches:
      - main

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build on aarch64
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Build artifacts
        id: build
        with:
          arch: aarch64
          distro: alpine_latest

          githubToken: ${{ github.token }}

          setup: |
            mkdir -p "${PWD}/artifacts"
            ls ${GITHUB_WORKSPACE}

          dockerRunArgs: |
            --volume ${PWD}/artifacts:/artifacts
            --volume ${GITHUB_WORKSPACE}:/workspace

          shell: /bin/sh

          install: |
            ls /workspace
            apk update
            apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib
            bash /workspace/automation/dotnet-install.sh -c 5.0

          run: |
            dotnet publish /workspace/CSharpMongoGraphqlSubscriptions.csproj -c Release -o /artifacts

      - name: Publish artifacts
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ${PWD}/artifacts.zip ${PWD}/artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: ${PWD}/artifacts.zip
