name: Build C# Backend

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.*

jobs:
  build_job:
    runs-on: ubuntu-20.04
    name: Build on aarch64
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup environment variables
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Publish artifacts
        run: dotnet publish ${{ github.workspace }}/CSharpMongoGraphqlSubscriptions.csproj -c Release -r linux-arm64 -o ${{ github.workspace }}/brewcontroller-${{ env.RELEASE_VERSION }} --self-contained true

      - name: Archive artifacts
        run: tar -czvf ${{ github.workspace }}/brewcontroller.tar.gz -C ${{ github.workspace }} brewcontroller-${{ env.RELEASE_VERSION }}

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/brewcontroller.tar.gz
