name: Build C# Backend

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.*

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build_job:
    runs-on: ubuntu-20.04
    name: Build on aarch64
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup environment variables
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Cache project dependencies
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Publish artifacts
        run: dotnet publish ${{ github.workspace }}/CSharpMongoGraphqlSubscriptions.csproj -c Release -r linux-arm64 -o ${{ github.workspace }}/brewcontroller-${{ env.RELEASE_VERSION }} --self-contained true

      - name: Archive artifacts
        run: tar -czvf ${{ github.workspace }}/brewcontroller.tar.gz -C ${{ github.workspace }} brewcontroller-${{ env.RELEASE_VERSION }}

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/brewcontroller.tar.gz
